
server:
  port: 0

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: usuario-service
  cloud:
    config:
      enabled: false
