server:
  port: 8099

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/users/**
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/motorbikes/**
        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/cars/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP:192.168.2.6}
    hostname: ${HOST_IP:192.168.2.6}
